version: '3.8'
services:
  app:
    user: $UID:$GID
    build:
      context: .
      args:
          UID: $UID
          GID: $GID
          USERNAME: $USERNAME
    volumes:
      - "$SSH_AUTH_SOCK:/tmp/ssh-agent.sock"
    environment:
      SSH_AUTH_SOCK: "/tmp/ssh-agent.sock"